version: '3'
services:
  elm:
    image: ynishi/elm
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - 8000:8000
  elm-test:
    image: ynishi/elm
    command: elm-test
    volumes:
      - ./dev:/home/node/app
    ports:
      - 8001:8000
  elm-webpack:
    image: ynishi/elm:latest-webpack
    command: npm start
    volumes:
      - ./webpack:/home/node/app
    ports:
      - 8080:8080
